# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [129]:
np.full(100, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

python3 -c "import numpy; numpy.info(numpy.add)"

#### 5. Поменять 2 строки в матрице

In [48]:
a=np.arange(10).reshape(5,2)
arr=[]
for i in range(len(a)):
    arr.append(a[i])
arr[0], arr[-1]=arr[-1], arr[0]
b=np.array(arr)
b

array([[8, 9],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1]])

#### 6. Создать вектор со значениями от 10 до 100

In [5]:
np.arange(10, 101)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [6]:
np.arange(100)[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [187]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [57]:
a=np.array([1,2,3,4,5])
d=np.zeros(17)
d[::4]=a
d

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [9]:
np.ones((3, 3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [10]:
np.random.randn(9).reshape(3,3)

array([[-0.59789257, -1.51355958,  0.15623176],
       [-0.56241407, -1.11315842,  0.98463903],
       [-0.78413305, -0.05834102, -1.51460203]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [28]:
np.random.seed(42)
a=np.random.randn(100).reshape(10,10)
print(a.min(), a.max())

-2.6197451040897444 1.8522781845089378


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [29]:
a=np.random.randn(30)
a.mean()

0.05278690829770844

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [75]:
a=np.zeros(30).reshape(6,5)
a[:,0],a[:, -1],a[0, :],a[-1, :]=1,1,1,1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

:(

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [131]:
np.diag(np.arange(1, 5), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [93]:
a=np.zeros(64).reshape(8,8)
for i in range(len(a)):
    if i%2==0:
        a[i]=np.array(([0,1,0,1,0,1,0,1]))
    else:
        a[i]=np.array(([1,0,1,0,1,0,1,0]))
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [116]:
np.random.seed(42)
a=np.random.rand(6,7,8)
c=0
for i in range(len(a)):
    for j in range(len(a[i])):
        for k in range(len(a[i][j])):
            c+=1
            if c==100:
                print(i,j,k)
                break

1 5 3


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [3]:
a=np.tile(np.array([[1,0],[0,1]]), (4,4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [76]:
a=np.random.rand(5,3)
b=np.random.rand(3,2)
a.dot(b)

array([[0.85093315, 0.398226  ],
       [0.31146245, 0.55763024],
       [0.46629796, 0.98980051],
       [0.31956036, 0.60110859],
       [1.31749238, 0.93964994]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [78]:
a=np.array([1,3,6,3,4,12,4,531,90,7,4,5,6])
a[np.where((a>3) & (a<8))]=-a[np.where((a>3) & (a<8))]
a

array([  1,   3,  -6,   3,  -4,  12,  -4, 531,  90,  -7,  -4,  -5,  -6])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [135]:
a=list(range(5))
b=np.zeros(25).reshape(5,5)
for i in range(len(b)):
    b[i]=a
b.astype(int)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

-

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [55]:
np.random.seed(42)
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

#### 26. Отсортировать вектор

In [54]:
np.random.seed(42)
a=np.random.randn(10)
np.sort(a)

array([-0.46947439, -0.23415337, -0.23413696, -0.1382643 ,  0.49671415,
        0.54256004,  0.64768854,  0.76743473,  1.52302986,  1.57921282])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [185]:
np.random.seed(6)
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
np.allclose(a,b)

False

#### 28. Сделать массив неизменяемым

In [110]:
arr=[1,2,3,4,5,6]
arr=tuple(arr)

#### 29. Найти n наибольших значений в массиве

In [102]:
np.random.seed(42)
a=np.random.rand(20)
a=np.sort(a)
n=int(input())
for i in range(1,n+1):
    print(a[-i])

 5


0.9699098521619943
0.9507143064099162
0.8661761457749352
0.8324426408004217
0.7319939418114051


#### 30. Заменить максимальный элемент на ноль

In [98]:
np.random.seed(24)
a=np.random.rand(10)
a[np.where(a==a.max())]=0
a

array([0.9600173 , 0.69951205, 0.        , 0.2200673 , 0.36105635,
       0.73984099, 0.99645573, 0.31634698, 0.13654458, 0.38398001])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [4]:
a = np.zeros((10,10), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
a

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [210]:
np.random.seed(42)
a=list(range(10,21))
b=list(range(1,10))
C=np.zeros((len(a), len(b)))
for i in range(len(a)):
    for j in range(len(b)):
        C[i,j]=1/(a[i]-b[j])
C

array([[0.11111111, 0.125     , 0.14285714, 0.16666667, 0.2       ,
        0.25      , 0.33333333, 0.5       , 1.        ],
       [0.1       , 0.11111111, 0.125     , 0.14285714, 0.16666667,
        0.2       , 0.25      , 0.33333333, 0.5       ],
       [0.09090909, 0.1       , 0.11111111, 0.125     , 0.14285714,
        0.16666667, 0.2       , 0.25      , 0.33333333],
       [0.08333333, 0.09090909, 0.1       , 0.11111111, 0.125     ,
        0.14285714, 0.16666667, 0.2       , 0.25      ],
       [0.07692308, 0.08333333, 0.09090909, 0.1       , 0.11111111,
        0.125     , 0.14285714, 0.16666667, 0.2       ],
       [0.07142857, 0.07692308, 0.08333333, 0.09090909, 0.1       ,
        0.11111111, 0.125     , 0.14285714, 0.16666667],
       [0.06666667, 0.07142857, 0.07692308, 0.08333333, 0.09090909,
        0.1       , 0.11111111, 0.125     , 0.14285714],
       [0.0625    , 0.06666667, 0.07142857, 0.07692308, 0.08333333,
        0.09090909, 0.1       , 0.11111111, 0.125     ],


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [215]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [141]:
a=np.array([1,2,2,3,34,4,5,6,6,7,7])
for i in range(len(a)):
    print(a[i])

1
2
2
3
34
4
5
6
6
7
7


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [121]:
k=int(input())
j=int(input())
arr=[]
for i in range(j):
    a=float(input())
    arr.append(a)
ar1=[]
for i in range(j):
    d=abs(k-arr[i])
    ar1.append((d, arr[i]))
ar1.sort()
ar1[0][1]

 4
 5
 5
 4.08
 4.5
 2
 -1


4.08

#### 36. Преобразовать массив из float в int

In [128]:
a=np.array([1.09, 5.643, 7.09])
a.astype(int)

array([1, 5, 7])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

np.ndenumerate

#### 38. Случайно расположить p элементов в 2D массив

In [178]:
a=np.zeros((7,5))
p=4
for i in range(p):
    s=np.random.choice(len(a))
    v=np.random.choice(len(a[s]))
    a[s][v]=1
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 39. Отнять среднее из каждой строки в матрице

In [8]:
np.random.seed(42)
a=np.random.rand(3,3)
a=a-a.mean()
a

array([[-0.12471486,  0.45145933,  0.23273897],
       [ 0.09940351, -0.34323634, -0.34326046],
       [-0.44117136,  0.36692117,  0.10186004]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [147]:
a=np.random.rand(10, 5)
n=int(input())
a=a.reshape(5,10)
a[n]=np.sort(a[n])
a

 4


array([[0.13882717, 0.64087474, 0.18188008, 0.34566728, 0.89678841,
        0.47396164, 0.66755774, 0.17231987, 0.19228902, 0.04086862],
       [0.16893506, 0.27859034, 0.17701048, 0.08870253, 0.12063587,
        0.46077877, 0.20633372, 0.36426986, 0.50341727, 0.69039483],
       [0.03931214, 0.7994104 , 0.62790039, 0.08175903, 0.87357862,
        0.9208724 , 0.06107796, 0.27687765, 0.80620128, 0.74825969],
       [0.18452102, 0.20934932, 0.3704721 , 0.48452299, 0.61825477,
        0.36891364, 0.46253472, 0.74747094, 0.0366832 , 0.25243694],
       [0.10717201, 0.2424705 , 0.26924323, 0.37728416, 0.44741237,
        0.51167744, 0.53211349, 0.53261727, 0.71334959, 0.89520684]])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [165]:
a=np.array([[1, 2, 3, 0], [4, 5, 6,0], [7, 9, 6,0]])
a[::-1]

array([[7, 9, 6, 0],
       [4, 5, 6, 0],
       [1, 2, 3, 0]])

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [144]:
a=[1,2,3,4,5]
b=np.array([1,2,3,4,5,6,7,8,9,10,10,5,13,12,1])
b[a]=b[a]+1
b

array([ 1,  3,  4,  5,  6,  7,  7,  8,  9, 10, 10,  5, 13, 12,  1])

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

-

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [7]:
np.random.seed(42)
a = np.random.randint(0,100, (2,3,3,2))
summ = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(summ)

[[308 502 186]
 [209 321 418]]
